# site settings
name: 2HAAS
title: 2HAAS | Draw Your Imagination
description: "ART is related with HEART.. It's the imagination which is framed in a canvas. Arts have no boundaries. And it's an opportunity to show your imagination to the world with 2HAAS.. Publish your Arts With 2HAAS. And that's why we say 'Draw Your Imagination'.."
disqus_username: disqus_awXlUkG4f9


# advance settings
url: "https://2haas.ml"
baseurl: ""
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

permalink: /:tags/:title/

# pagination plugin
plugins:
  - jekyll-paginate
paginate: 6
paginate_path: /page-:num
source: .
destination: ./_site
permalink: /:title/

collections:
  authors:
    output: true
  categories:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "categories"
    values:
       layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude: [
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
]

