backend:
  name: git-gateway
  repo: 2hwd/m-ws
  branch: master
  site_domain: https://2haas.ml
media_folder: "assets/img/uploads"
public_folder: "images/uploads"
publish_mode: editorial_workflow
display_url: https://2haas.ml
logo_url: https://2haas.ml/favicon.ico
show_preview_links: true

